#+title: Stock Market Indices
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

Here we'll take a look at price and value-weighted stock indices. Say our index covers two stocks (A and B) with the following number of shares outstanding.

#+TBLNAME: shares
| Stock | Shares Outstanding |
|-------+--------------------|
| A     |                 50 |
| B     |                300 |
|-------+--------------------|

We'll consider the price of each stock over two days:

#+NAME: Stock Prices
#+TBLNAME: prices
| Stock | Price Day 1 ($) | Price Day 2 ($) |
|-------+-----------------+-----------------|
| A     |             200 |             190 |
| B     |              30 |              35 |
|-------+-----------------+-----------------|

** Price-Weighted Index (DJIA)

To construct a price-weighted index we can simply average the prices each day (sum them and here divide by 2).  The only complication arises when a stock in the index splits.  We don't want the split to affect the index value, so we adjust the divisor.  

For example, say stock A splits on day 2.  For the index value to stay the same, we have to make the divisor (d):

$$112.5=\frac{35 + 95}{d} \Rightarrow d = \frac{130}{112.5} = 1.1555$$

Obviously, in a price-weighted index 

#+BEGIN_QUOTE
The stock with the highest price has the largest effect on the index.
#+END_QUOTE

This may be undesirable, depending on your use for the index, because a stock's price is not a meaningful value---a high price does not mean a large market cap.

A price weighted-index tracks:

#+BEGIN_QUOTE
The performance of a portfolio comprised of one share of each stock in the index.
#+END_QUOTE


#+NAME: Price-Weighted Index
#+TBLNAME: price-index
|      Day |  Index Value |
|----------+--------------|
|        1 |          115 |
|        2 |        112.5 |
|----------+--------------|
| % Change | -0.021739130 |
|----------+--------------|
#+TBLFM: @2$2=(remote(prices,@2$2)+remote(prices,@3$2))/2::@3$2=(remote(prices,@2$3)+remote(prices,@3$3))/2::@4$2=@3$2/@2$2 - 1

** Value-Weighted (S&P 500)

A value-weighted index considers the market cap of a firm, rather than its price.  This is a more reasonable measure than price.  Note the market cap of a firm is not its total size (which is the enterprise value and includes debt).

#+BEGIN_QUOTE
The stock with the highest market cap has the largest effect on the index.
#+END_QUOTE

Generally, the larger your portfolio the more similar your portfolio weights for each stock will be to the weights in the market index.  This is why the performance of large portfolios are compared to the market index (which is value-weighted).

#+TBLNAME: value-index
|      Day | Market Cap A | Market Cap B | Total Market Cap | Index Value |
|----------+--------------+--------------+------------------+-------------|
|        1 |        10000 |         9000 |            19000 |         100 |
|        2 |         9500 |        10500 |            20000 |   105.26316 |
|----------+--------------+--------------+------------------+-------------|
| % Change |              |              |                  |   0.0526316 |
|----------+--------------+--------------+------------------+-------------|
#+TBLFM: @2$2=(remote(prices,@2$2)*remote(shares,@2$2))::@2$3=(remote(prices,@3$2)*remote(shares,@3$2))::@3$2=(remote(prices,@2$3)*remote(shares,@2$2))::@3$3=(remote(prices,@3$3)*remote(shares,@3$2))::@2$4=@2$2+@2$3::@3$4=@3$2+@3$3::@3$5=(@3$4/@2$4)*@2$5::@4$5=@3$5/@2$5-1


*** Index Creation

To create a market-value index we choose some start date and starting value---commonly 100. 

 $100*\frac{P_1}{P_0}\frac{P_2}{P_1}\frac{P_3}{P_2}\frac{P_4}{P_3}\frac{P_5}{P_4} = 100\frac{P_5}{P_0}$


** Equal-Weight Indices

There is a class of indices where each asset in the index has an equal weight in the index value. These indices are fairly unimportant.  

